name: Deploy React Portfolio to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: suri  # React app folder

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Configure Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Deploy to GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.GH_PERSONAL_TOKEN }}   # Pass GitHub Actions token
        run: npx gh-pages -d build -b gh-pages --cname venkatasaikiransuri.online -r https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git